version: '3.9'

services:
  migrations:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    command: -path=/migrations/ -database=postgresql://rvl:rvl@postgres:5432/rvl?sslmode=disable up
    depends_on:
      postgres:
        condition: service_healthy
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      - RVL_DB_HOST=postgres
      - RVL_DB_PORT=5432
      - RVL_DB_USERNAME=rvl
      - RVL_DB_PASSWORD=rvl
      - RVL_DBNAME=rvl
    depends_on:
      migrations:
        condition: service_completed_successfully

  postgres:
    image: postgres:14
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rvl" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=rvl
      - POSTGRES_PASSWORD=rvl
      - POSTGRES_DB=rvl