---
apiVersion: v1
kind: Namespace
metadata:
  name: ${DB_NAMESPACE}
---
apiVersion: v1
kind: Service
metadata:
  name: ${DB_SVC_NAME}
  namespace: ${DB_NAMESPACE}
spec:
  type: ExternalName
  externalName: ${CLOUDSQL_HOST}
  ports:
  - port: 5432