---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: birthday-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: birthday-app
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50