{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "birthday_chart.fullname" . }}-migrations
  labels:
    {{- include "birthday_chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: birthday-migrations
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - migrate -path=/migrations/ -database=postgresql://${RVL_DB_USERNAME}:${RVL_DB_PASSWORD}@${RVL_DB_HOST}:${RVL_DB_PORT}/${RVL_DB_DBNAME}?sslmode=disable up
          env:
            - name: RVL_DB_HOST
              value: {{ .Values.appConfig.dbHost }}
            - name: RVL_DB_PORT
              value: {{ .Values.appConfig.dbPort | quote }}
            - name: RVL_DB_USERNAME
              value: {{ .Values.appConfig.dbUser }}
            - name: RVL_DB_PASSWORD
              value: {{ .Values.appConfig.dbPassword }}
            - name: RVL_DB_DBNAME
              value: {{ .Values.appConfig.dbName }}
      restartPolicy: Never
{{- end }}