apiVersion: v1
kind: Service
metadata:
  name: {{ include "birthday_chart.fullname" . }}
  labels:
    {{- include "birthday_chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "birthday_chart.selectorLabels" . | nindent 4 }}
